name: flutter_multitool
description: Some widget extensions and common classes for improve developer experience
version: 0.2.0
repository: "https://github.com/CoMatu/flutter_multitool.git"

environment:
  sdk: ^3.6.0

dependencies:
  bloc: ^9.0.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null
