name: flutter_multitool
description: Some widget extensions and common classes for improve developer experience
version: 0.0.3
repository: 'https://github.com/CoMatu/flutter_multitool.git'

environment:
  sdk: '>=2.18.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  bloc: ^8.1.0
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0

dev_dependencies:
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter: null


